version: "3"
services:
  redis:
    image: redis:6.2.5-alpine
    container_name: redis
    hostname: redis
    volumes:
      - redis_volume:/data
    networks:
      - tartarus_network
    restart: always
  postgres:
    image: postgres:13.5-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    env_file:
      - ./env/postgres.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./configs/postgres/postgres.conf:/etc/postgresql/postgresql.conf
    networks:
      - tartarus_network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pgadmin
    ports:
      - "5454:80"
    env_file:
      - ./env/pgadmin.env
    networks:
      - tartarus_network
    restart: always

volumes:
  postgres_volume:
  redis_volume:

networks:
  tartarus_network:
    external: true
